name: Format and Deploy

on:
  push:

jobs:
  format-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Use latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
